spring.application.name=blockchain-service
alchemy.url=https://eth-sepolia.g.alchemy.com/v2/alch_q6sfa8fa83qumXuBvl7xb
contract.address=0x1220b92B69B4284BA2875A5D89b341FEb3316582
# 1 - 0x5019eE0bc2D7243b5864dB67254aAEF42030c91A
wallet.privateKey=f06800550f7f8d82126c510e4c368c4b3e1ad210efee8587e9dc3b2a22d8b86a
#
chain.id=11155111

server.port=8052
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator — expose health endpoint for system health monitoring
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.enabled=true

